
name: Deploy Next.js site to Pages

on:

  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install NPM Dependencies
        run: npm i
      - name: Build Project
        run: npm run build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./out
      # deployed job
 deploy:
    environment:
      name: github-pages
     
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./out

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.PROJECT_DEPLOY}}
          publish_dir: ./pages/index.js    
